"""empty message

Revision ID: 0e4a21058cde
Revises: 9769bcd2ee39
Create Date: 2024-11-25 22:31:31.075207

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0e4a21058cde'
down_revision = '9769bcd2ee39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('additional_info', sa.Text(), nullable=True))
        batch_op.drop_index('email')
        batch_op.create_foreign_key(None, 'user', ['id'], ['id'])
        batch_op.drop_column('email')
        batch_op.drop_column('birth_date')
        batch_op.drop_column('last_name')
        batch_op.drop_column('password')
        batch_op.drop_column('first_name')
        batch_op.drop_column('phone_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', mysql.VARCHAR(length=20), nullable=False))
        batch_op.add_column(sa.Column('first_name', mysql.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('password', mysql.VARCHAR(length=200), nullable=False))
        batch_op.add_column(sa.Column('last_name', mysql.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('birth_date', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('email', mysql.VARCHAR(length=100), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index('email', ['email'], unique=True)
        batch_op.drop_column('additional_info')

    # ### end Alembic commands ###
