"""Add free_times to Master model

Revision ID: 550d6238af41
Revises: 4bccd5eb0710
Create Date: 2024-12-15 18:28:55.791708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '550d6238af41'
down_revision = '4bccd5eb0710'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('master', schema=None) as batch_op:
        batch_op.add_column(sa.Column('free_times', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('master', schema=None) as batch_op:
        batch_op.drop_column('free_times')

    # ### end Alembic commands ###
